include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_redundant_argument_values
    - unnecessary_null_checks
    - use_string_buffers
    - sort_pub_dependencies
